TRWLASystemMaster/TRWLASystemMaster/Controllers/VolunteerTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TRWLASystemMaster.Models.DB;

namespace TRWLASystemMaster.Controllers
{
    public class VolunteerTypesController : Controller
    {
        private TWRLADB_Staging_V2Entities8 db = new TWRLADB_Staging_V2Entities8();

        // GET: VolunteerTypes
        public ActionResult Index(string searchStringVS)
        {
            var voltype = from vu in db.VolunteerTypes
                          select vu;

            if (!String.IsNullOrEmpty(searchStringVS))
            {
                voltype = voltype.Where(s => s.VolunteerType_Description.Contains(searchStringVS));

            }

            return View(voltype.ToList());
        }

        // GET: VolunteerTypes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VolunteerType volunteerType = db.VolunteerTypes.Find(id);
            if (volunteerType == null)
            {
                return HttpNotFound();
            }
            return View(volunteerType);
        }

        // GET: VolunteerTypes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: VolunteerTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "VolunteerTypeID,VolunteerType_Description")] VolunteerType volunteerType)
        {
            if (ModelState.IsValid)
            {
                db.VolunteerTypes.Add(volunteerType);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(volunteerType);
        }

        // GET: VolunteerTypes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VolunteerType volunteerType = db.VolunteerTypes.Find(id);
            if (volunteerType == null)
            {
                return HttpNotFound();
            }
            return View(volunteerType);
        }

        // POST: VolunteerTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "VolunteerTypeID,VolunteerType_Description")] VolunteerType volunteerType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(volunteerType).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(volunteerType);
        }

        // GET: VolunteerTypes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VolunteerType volunteerType = db.VolunteerTypes.Find(id);
            if (volunteerType == null)
            {
                return HttpNotFound();
            }
            return View(volunteerType);
        }

        // POST: VolunteerTypes/Delete/5
        [HttpPost, ActionName("Details")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            VolunteerType volunteerType = db.VolunteerTypes.Find(id);
            db.VolunteerTypes.Remove(volunteerType);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TRWLASystemMaster/TRWLASystemMaster/Views/VolunteerTypes/Create.cshtml
@model TRWLASystemMaster.Models.DB.VolunteerType

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/VolunteerLoggedInPage.cshtml";
}


<div class="jumbotron">
    <h1>Create a New Volunteer Type</h1>
    <div class="quoteform"></div>
    <div class="quote1form"></div>
    <div class="quote2form"></div>
</div>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Description", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VolunteerType_Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VolunteerType_Description, "", new { @class = "text-danger" })
            </div>
        </div>

    </div>


        <div class="modal fade" id="Create" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title" id="myModalLabel">Create Volunteer Type?</h4>
                    </div>
                    <div class="modal-body">
                        Are you sure you want to create this volunteer type?
                    </div>
                    <div class="modal-footer form-inline">
                        <div class="form-actions no-color form-group">
                            <button data-toggle="tooltip" title="Confirm" type="submit" value="Create" class="btn">Confirm</button>
                        </div>
                        <div class="form-actions no-color  form-group">
                            <button data-toggle="tooltip" title="Make Ammendments" type="button" class="btn" data-dismiss="modal">Edit</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        }

        <div class="form-inline" style="float:right; margin-bottom:20px; margin-top:60px;">
            <div class="form-group">
                <div style="margin-right:5px;" data-toggle="tooltip" title="Save Volunteer Type">
                    <button class="btn btn-default" data-toggle="modal" data-target="#Create">
                        Save
                    </button>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10" data-toggle="tooltip" title="Return to Volunteer Types">
                    <div>
                        <button type="button" class="btn" onclick="location.href='@Url.Action("Index", "VolunteerTypes")'"><i class="fa fa-arrow-left" aria-hidden="true"></i></button>
                    </div>
                </div>
            </div>
        </div>

TRWLASystemMaster/TRWLASystemMaster/Views/VolunteerTypes/Delete.cshtml
@model TRWLASystemMaster.Models.DB.VolunteerType

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/VolunteerLoggedInPage.cshtml";
}

<div class="jumbotron">
    <h1>Delete a Volunteer Type</h1>
    <div class="quoteform"></div>
    <div class="quote1form"></div>
    <div class="quote2form"></div>
</div>

<h3>Are you sure you want to delete this?</h3>

<div>

    <dl class="dl-horizontal">
        <dt>
            @Html.Label("Description")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VolunteerType_Description)
        </dd>

    </dl>


</div>

<div class="form-inline" style="float:right; margin-bottom:20px; margin-top:60px;">
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">

            <div>
                <button type="button" class="btn" onclick="location.href='@Url.Action("Index", "StudentTypes")'">Return</button>

            </div>

        </div>
    </div>
</div>

<div class="form-inline" style="float:right; margin-bottom:20px; margin-top:60px;">
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <div>
                <div>
                    @using (Html.BeginForm())
            {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                            <input type="submit" value="Delete" class="btn btn-default" />

                        </div>
                    }
                </div>

            </div>
        </div>
    </div>
</div>

TRWLASystemMaster/TRWLASystemMaster/Views/VolunteerTypes/Details.cshtml
@model TRWLASystemMaster.Models.DB.VolunteerType

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/VolunteerLoggedInPage.cshtml";
}

<div class="jumbotron">
    <h1>Volunteer Type Details</h1>
    <div class="quoteform"></div>
    <div class="quote1form"></div>
    <div class="quote2form"></div>
</div>


<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.Label("Description")
        </dt>

        <dd class="form-control" style="width:200px;  overflow-y:auto; margin-bottom:10px;">
            @Html.DisplayFor(model => model.VolunteerType_Description)
        </dd>

    </dl>
</div>
@*<p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.VolunteerTypeID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>*@


<div style="float:right; margin-bottom:20px; margin-top:10px;">
    <div class="form-inline">
        <div class="form-group" data-toggle="tooltip" title="Update">
            <button  type="button" class="btn" onclick="location.href='@Url.Action("Edit", "VolunteerTypes", new { id = Model.VolunteerTypeID })'"><i class="fa fa-pencil" aria-hidden="true"></i></button>
        </div>
        <div class="form-group" data-toggle="tooltip" title="Delete">
            <button class="btn btn-default" data-toggle="modal" data-target="#Delete">
                <i class="fa fa-trash" aria-hidden="true"></i>
            </button>
        </div>
        <div class="form-group" data-toggle="tooltip" title="Return to Volunteer Types">
            <button type="button" class="btn" onclick="location.href='@Url.Action("Index", "VolunteerTypes")'"><i class="fa fa-arrow-left" aria-hidden="true"></i></button>
        </div>
    </div>
</div>

<div class="modal fade" id="Delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Delete Volunteer Type</h4>
            </div>
            <div class="modal-body">
                Are you sure that you want to delete this volunteer type?
            </div>
            <div class="modal-footer form-inline">
                @using (Html.BeginForm())
            {
                    @Html.AntiForgeryToken()
                    <div class="form-actions no-color form-group" data-toggle="tooltip" title="Delete">
                        <button  type="submit" value="Delete" class="btn btn-default btn-simple form-group">Delete</button>
                    </div>
                    <div class="form-group" data-toggle="tooltip" title="Make Changes">
                        <button  type="button" class="btn btn-default btn-simple form-group" data-dismiss="modal">Close</button>
                    </div>
                }

            </div>
        </div>
    </div>
</div>

TRWLASystemMaster/TRWLASystemMaster/Views/VolunteerTypes/Edit.cshtml
@model TRWLASystemMaster.Models.DB.VolunteerType

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/VolunteerLoggedInPage.cshtml";
}


<div class="jumbotron">
    <h1>Update a Volunteer Type</h1>
    <div class="quoteform"></div>
    <div class="quote1form"></div>
    <div class="quote2form"></div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.VolunteerTypeID)

        <div class="form-group">
            <label class="control-label col-md-2"> Description </label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.VolunteerType_Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VolunteerType_Description, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="modal fade" id="Create" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Update Volunteer Type</h4>
                </div>
                <div class="modal-body">
                    Are you sure that you want to update this volunteer type?
                </div>
                <div class="modal-footer form-inline">
                    <div class="form-actions no-color form-group"  data-toggle="tooltip" title="Update Volunteer Type">
                        <button type="submit" value="Create" class="btn">Confirm</button>
                    </div>
                    <div class="form-group"c data-toggle="tooltip" title="Make Changes">
                        <button type="button" class="btn" data-dismiss="modal">Edit</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<div class="form-inline" style="float:right; margin-bottom:20px; margin-top:60px;">
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10"  data-toggle="tooltip" title="Save Changes">
            <button class="btn btn-default" data-toggle="modal" data-target="#Create">
                Save
            </button>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <div  data-toggle="tooltip" title="Return to Volunteer Type Details">
                <button type="button" class="btn" onclick="location.href='@Url.Action("Details", "VolunteerTypes", new { id = Model.VolunteerTypeID } )'"><i class="fa fa-arrow-left" aria-hidden="true"></i></button>

            </div>
        </div>
    </div>
</div>

TRWLASystemMaster/TRWLASystemMaster/Views/VolunteerTypes/Index.cshtml
@model IEnumerable<TRWLASystemMaster.Models.DB.VolunteerType>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/VolunteerLoggedInPage.cshtml";
}




<div class="jumbotron">

    <h1> Volunteer Types</h1>
    <div class="quoteform"></div>
    <div class="quote1form"></div>
    <div class="quote2form"></div>
</div>


@* Search Button for VolunteerType Description  '*@
<h2 style="z-index:100; position:relative; background-color:transparent;">Search Volunteer Types</h2>
@using (Html.BeginForm())
{
    <div class="form-inline" style="margin-bottom:10px;">
        <p data-toggle="tooltip" title="Search by name" class="form-group">
            @Html.TextBox("searchStringVS", "", new { placeholder = "Name of Volunteer Type", @class = "form-control", style = "width:100%;" })
        </p>

        <p class="form-group">
            <button data-toggle="tooltip" title="Search" type="submit" value="Search" class="btn"><i class="fa fa-search" aria-hidden="true" style="color:black;"></i></button>
        </p>
    </div>
}


<table class="table">
    <tr>
        <th>
            Volunteer Type     @*@Html.DisplayNameFor(model => model.VolunteerType_Description)*@
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.VolunteerType_Description)
            </td>
            <td>
                <a href="@Url.Action("Details", new { id=item.VolunteerTypeID })" data-toggle="tooltip" title="Details"><i class="fa fa-info-circle" aria-hidden="true"></i></a>
            </td>
        </tr>
    }

</table>



<div class="form-inline" style="float:right; margin-bottom:20px; margin-top:10px;">
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10"  data-toggle="tooltip" title="Return to Volunteers">
            <div>
                <button type="button" class="btn" onclick="location.href='@Url.Action("Volunteers", "SYSUserProfiles")'"><i class="fa fa-arrow-left" aria-hidden="true"></i></button>

            </div>
        </div>
    </div>
</div>


<div class="form-inline" style="float:right; margin-bottom:20px; margin-top:10px;">
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10"  data-toggle="tooltip" title="Create Volunteer Type">
            <div>
                <button type="button" class="btn" onclick="location.href='@Url.Action("Create", "VolunteerTypes")'"><i class="fa fa-plus" aria-hidden="true"></i></button>

            </div>
        </div>
    </div>
</div>