TRWLASystemMaster/TRWLASystemMaster/Models/DB/Content.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TRWLASystemMaster.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Content()
        {
            this.ComEngEvents = new HashSet<ComEngEvent>();
            this.GenEvents = new HashSet<GenEvent>();
            this.Lectures = new HashSet<Lecture>();
        }
    
        public int ContentID { get; set; }
        [Required(ErrorMessage = "A name for the content is required")]
        [Display(Name = "name")]
        [StringLength(50, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 2)]
        public string Content_Name { get; set; }
        public string Content_Link { get; set; }
        public int Content_Status { get; set; }
        [Required(ErrorMessage = "A description for the content is required")]
        [Display(Name = "contdescriptionent")]
        [StringLength(300, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 2)]
        public string Content_Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComEngEvent> ComEngEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GenEvent> GenEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lecture> Lectures { get; set; }
    }
}

TRWLASystemMaster/TRWLASystemMaster/Controllers/ContentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TRWLASystemMaster.Models;
using System.IO;
using TRWLASystemMaster.Models.DB;

namespace TRWLASystemMaster.Controllers
{
    public class ContentsController : Controller
    {
        private TWRLADB_Staging_V2Entities8 db = new TWRLADB_Staging_V2Entities8();

        //public FileActionResult Downloads()
        //{
        //    var dir = new System.IO.DirectoryInfo(Server.MapPath("~/App_Data/Images/"));
        //    System.IO.FileInfo[] fileNames = dir.GetFiles("*.*");
        //    List<string> items = new List<string>();

        //    foreach (var file in fileNames)
        //    {
        //        items.Add(file.Name);
        //    }

        //    return View(items);
        //}

        // GET: Contents1
        public ActionResult Index(string sortOrder, string searchString, string locked, string unlocked, string all)
        {
            try
            {
                ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
                ViewBag.SurnameSortParm = String.IsNullOrEmpty(sortOrder) ? "sur_desc" : "Surname";
                ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";


                var content = from s in db.Contents
                              select s;

                if (!String.IsNullOrEmpty(searchString))
                {
                    content = content.Where(s => s.Content_Name.Contains(searchString));
                }

                if (!String.IsNullOrEmpty(locked))
                {

                    content = content.Where(s => s.Content_Status.Equals(1));
                }

                if (!String.IsNullOrEmpty(unlocked))
                {

                    content = content.Where(s => s.Content_Status.Equals(0));
                }

                if (!String.IsNullOrEmpty(all))
                {

                    content = content.Where(s => s.Content_Status.Equals(0) || s.Content_Status.Equals(1));
                }


                switch (sortOrder)
                {
                    case "name_desc":
                        content = content.OrderByDescending(s => s.Content_Name);
                        break;
                    case "sur_desc":
                        content = content.OrderByDescending(s => s.Content_Name);
                        break;
                    case "Surname":
                        content = content.OrderByDescending(s => s.Content_Name);
                        break;
                    default:
                        content = content.OrderBy(s => s.Content_Name);
                        break;
                }

                return View(content.ToList());
            }
            catch (Exception)
            {
                return RedirectToAction("ErrorPage", "TRWLASchedules");
            }
        }

        // GET: Contents1/Details/5
        public ActionResult Details(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Content content = db.Contents.Find(id);
                if (content == null)
                {
                    return HttpNotFound();
                }

                TempData["Image"] = id;
                return View(content);
            }
            catch (Exception)
            {
                return RedirectToAction("ErrorPage", "TRWLASchedules");
            }
        }

        public FilePathResult Download()
        {
                int id = Convert.ToInt32(TempData["Image"]);
                TempData["Image"] = id;
                Content contnents = db.Contents.Find(id);

                return new FilePathResult(contnents.Content_Link, System.Net.Mime.MediaTypeNames.Application.Pdf);

        }

        public FilePathResult Download2()
        {
                return new FilePathResult("~\\Help Manual\\User Manual - PDF.pdf", System.Net.Mime.MediaTypeNames.Application.Pdf);

        }

        // GET: Contents1/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Contents1/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ContentID,Content_Name,Content_Link,Content_Status,Content_Description")] Content content)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    int i = db.Contents.Count();

                    if (i != 0)
                    {
                        int k = db.Contents.Max(p => p.ContentID);
                        int max = k + 1;
                        AuditLog myAudit = new AuditLog();
                        myAudit.DateDone = DateTime.Now;
                        myAudit.TypeTran = "Create";
                        myAudit.SYSUserProfileID = (int)Session["User"];
                        myAudit.TableAff = "Content";
                        db.AuditLogs.Add(myAudit);

                        content.Content_Status = 1;
                        try
                        {
                            if (Request.Files.Count > 0)
                            {
                                var file = Request.Files[0];

                                if (file != null && file.ContentLength > 0)
                                {
                                    var fileName = Path.GetFileName(file.FileName);

                                    if (fileName.Contains(".pdf"))
                                    {
                                        var path = Path.Combine(Server.MapPath("~/Image/"), fileName);
                                        content.Content_Link = path.ToString(); ;
                                        file.SaveAs(path);
                                    }
                                    else
                                    {
                                        TempData["Notice"] = "Select a pdf document to upload";
                                        return View("Create");
                                    }
                                }

                                ViewBag.Message = "File Uploaded Successfully!!";
                            }
                            else
                            {
                                TempData["Error"] = "Please upload content.";
                                return View();
                            }
                        }
                        catch
                        {
                            ViewBag.Message = "File upload failed!!";
                        }


                        content.ContentID = max;
                        db.Contents.Add(content);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else if (i == 0)
                    {

                        AuditLog myAudit = new AuditLog();
                        myAudit.DateDone = DateTime.Now;
                        myAudit.TypeTran = "Create";
                        myAudit.SYSUserProfileID = (int)Session["User"];
                        myAudit.TableAff = "Content";
                        db.AuditLogs.Add(myAudit);

                        try
                        {
                            if (Request.Files.Count > 0)
                            {
                                var file = Request.Files[0];

                                if (file != null && file.ContentLength > 0)
                                {
                                    var fileName = Path.GetFileName(file.FileName);
                                    var path = Path.Combine(Server.MapPath("~/Images/"), fileName);
                                    content.Content_Link = path.ToString();
                                    file.SaveAs(path);
                                }
                            }
                            ViewBag.Message = "File Uploaded Successfully!!";
                        }
                        catch
                        {
                            ViewBag.Message = "File upload failed!!";
                        }

                        db.Contents.Add(content);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }

                }

                return View(content);
            }
            catch (Exception)
            {
                return RedirectToAction("ErrorPage", "TRWLASchedules");
            }
        }





        // GET: Contents1/Edit/5
        public ActionResult Edit(int? id)
        {
            try {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Content content = db.Contents.Find(id);
                if (content == null)
                {
                    return HttpNotFound();
                }
                return View(content);
            }
            catch (Exception)
            {
                return RedirectToAction("ErrorPage", "TRWLASchedules");
            }
        }

        // POST: Contents1/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

TRWLASystemMaster/TRWLASystemMaster/Views/Contents/Create.cshtml
@model TRWLASystemMaster.Models.DB.Content

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/VolunteerLoggedInPage.cshtml";
}

<div class="jumbotron">
    <h1>Upload Content</h1>

    <div class="quoteform"></div>
    <div class="quote1form"></div>
    <div class="quote2form"></div>
</div>



@using (Html.BeginForm("Create","Contents", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Name", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="margin-left:200px;">
            <p>Please ensure the content you choose in a pdf format.</p>
        </div>

        <div class="form-group">
            @Html.Label("Upload Content", new { @class = "control-label col-md-2" })
            <div class="editor-field col-md-10">
                <input class="btn;" type="file" name="file" id="user_profile_pic" required="required" />
                @if (TempData["Error"] != null)
                {
                    <p>@TempData["Error"]</p>
                }

                @if (TempData["Notice"] != null)
                {
                    @TempData["Notice"]
                }
            </div>
        </div>

        


        <div class="form-group">
            @Html.Label("Description", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content_Description, new { htmlAttributes = new {maxlength = 300, @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content_Description, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="modal fade" id="Create" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Upload Content</h4>
                </div>
                <div class="modal-body" data-toggle="tooltip" title="Upload Content">
                    Are you sure that you want to upload this content?
                </div>
                <div class="modal-footer form-inline">
                    <div class="form-actions no-color form-group " data-toggle="tooltip" title="Upload">
                        <button type="submit" value="Create" class="btn">Upload Content</button>
                    </div>
                    <div class="form-group" data-toggle="tooltip" title="Make Changes">
                        <button type="button" class="btn" data-dismiss="modal">Edit</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    
}

<div class="form-inline" style="float:right; margin-bottom:20px; margin-top:10px;">
    <div class="form-group">
        <div style="margin-right:5px;" data-toggle="tooltip" title="Save Content">
            <button class="btn btn-default" data-toggle="modal" data-target="#Create">
                Save
            </button>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10 " >
            <button data-toggle="tooltip" title="Return to Contents" type="button" class="btn" onclick="location.href='@Url.Action("Index", "Contents")'"><i class="fa fa-arrow-left" aria-hidden="true"></i></button>
        </div>
    </div>
</div>

TRWLASystemMaster/TRWLASystemMaster/Views/Contents/Details.cshtml
@model TRWLASystemMaster.Models.DB.Content

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/VolunteerLoggedInPage.cshtml";
}

<div class="jumbotron">
    <h1>@Html.DisplayFor(model => model.Content_Name) Information</h1>

    <div class="quoteform"></div>
    <div class="quote1form"></div>
    <div class="quote2form"></div>
</div>

@if (TempData["notice"] != null)
{
    <p>@TempData["notice"]</p>
}

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.Label("Name:")
        </dt>

        <dd class="form-control" style="width:200px; height:auto; margin-bottom:10px;">
            @Html.DisplayFor(model => model.Content_Name)
        </dd>

        <dt>
            @Html.Label("Status:")
        </dt>

        <dd class="form-control" style="width:200px; height:32px; margin-bottom:10px;">
            @if (Model.Content_Status == 1)
            {
                <p>Locked</p>
            }
            @if (Model.Content_Status == 0)
            {
                <p>Unlocked</p>
            }

        </dd>
        <dt>
            @Html.Label("Description:")
        </dt>

        <dd class="form-control" style="width:200px; height:auto; margin-bottom:10px;">
            @Html.DisplayFor(model => model.Content_Description)
        </dd>
        <dt>
            @Html.Label("Download Content:")
        </dt>
        <dd>
            @using (Html.BeginForm("Download", "Contents", FormMethod.Get))
            {
                <button formtarget="_blank" data-toggle="tooltip" title="Download Content" type="submit" value="Download Content" class="btn" style="width:200px;"><i class="fa fa-arrow-down" aria-hidden="true"></i></button> }
        </dd>

    </dl>

</div>
<div class="form-inline" style="float:right; margin-bottom:20px; margin-top:10px;">
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10" >
            <div data-toggle="tooltip" title="Update">
                <button type="button" class="btn" onclick="location.href='@Url.Action("Edit", "Contents", new { id = Model.ContentID })'"><i class="fa fa-pencil" aria-hidden="true"></i></button>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10" data-toggle="tooltip" title="Delete">
            <button class="btn" data-toggle="modal" data-target="#Delete">
                <i class="fa fa-trash" aria-hidden="true"></i>
            </button>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10 " data-toggle="tooltip" title="Return to Content">
            <div>
                <button type="button" class="btn" onclick="location.href='@Url.Action("Index", "Contents")'"><i class="fa fa-arrow-left" aria-hidden="true"></i></button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="Delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Delete @Html.DisplayFor(model => model.Content_Name)</h4>
            </div>
            <div class="modal-body">
                Are you sure that you want to delete @Html.DisplayFor(model => model.Content_Name)'s Information off of the system?
            </div>
            <div class="modal-footer form-inline">
                @using (Html.BeginForm())
            {
                    @Html.AntiForgeryToken()
                    <div class="form-actions no-color form-group " data-toggle="tooltip" title="Delete">
                        <button type="submit" value="Delete" class="btn btn-default btn-simple form-group">Delete Content</button>
                    </div>
                    <div class="form-group" data-toggle="tooltip" title="Cancel Deletion">
                        <button type="button" class="btn btn-default btn-simple form-group" data-dismiss="modal">Cancel</button>
                    </div>
                }
                
                </div>
            </div>
        </div>
    </div>

TRWLASystemMaster/TRWLASystemMaster/Views/Contents/Edit.cshtml
@model TRWLASystemMaster.Models.DB.Content

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/VolunteerLoggedInPage.cshtml";
}

<div class="jumbotron">
    <h1>Update @Html.DisplayFor(model => model.Content_Name)</h1>
    <div class="quoteform"></div>
    <div class="quote1form"></div>
    <div class="quote2form"></div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ContentID)

        <div class="form-group">
            @Html.Label("Name", new { @class = "control-label col-md-2" })
            <div data-toggle="tooltip" title="Update the Content Name">
                @Html.EditorFor(model => model.Content_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Content Status", new { @class = "control-label col-md-2" })
            <div style="width:50%;" class="row">
                <div>
                    <i data-toggle="tooltip" title="This will lock the content.
                       Students won't be able to view it." class="fa fa-lock" aria-hidden="true"></i>  @Html.RadioButtonFor(model => model.Content_Status, 1)
                </div>
                <div>
                    <i data-toggle="tooltip" title="This unlock the content.
                       Students will be able to view it." class="fa fa-unlock" aria-hidden="true"></i> @Html.RadioButtonFor(model => model.Content_Status, 0)
                </div>
                @Html.ValidationMessageFor(model => model.Content_Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Content Description", new { @class = "control-label col-md-2" })
            <div data-toggle="tooltip" title="Update the Content Description" style="width:50%;">
                @Html.TextAreaFor(model => model.Content_Description, new { maxlength = 300, @class = "form-control", @style = "border: 1px solid #E3E3E3; color: #2c2c2c; width:280px; height:200px;" })
                @Html.ValidationMessageFor(model => model.Content_Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div data-toggle="tooltip" title="Update the Content Name" >
                @Html.HiddenFor(model => model.Content_Link, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content_Link, "", new { @class = "text-danger" })
            </div>
        </div>

    </div>

    <div class="modal fade" id="Create" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Update Content</h4>
                </div>
                <div class="modal-body">
                    Are you sure that you want to update this Content?
                </div>
                <div class="modal-footer form-inline">
                    <div class="form-actions no-color form-group">
                        <button data-toggle="tooltip" title="Update Content" type="submit" value="Create" class="btn">Confirm</button>
                    </div>
                    <div class="form-group">
                        <button data-toggle="tooltip" title="Make Changes" type="button" class="btn" data-dismiss="modal">Edit</button>
                    </div>
                    </div>
                </div>
            </div>
        </div>
        }
        <div class="form-inline" style="float:right; margin-bottom:10px; margin-top:10px;">
            <div class="form-group">
                <div style="margin-right:5px;" data-toggle="tooltip" title="Update">
                    <button class="btn btn-default" data-toggle="modal" data-target="#Create">
                        Save
                    </button>
                </div>
            </div>
            <div class="form-group" >
                <button data-toggle="tooltip" title="Return to TRWLA Content" type="button" class="btn" onclick="location.href='@Url.Action("Details", "Contents", new { id = Model.ContentID } )'"><i class="fa fa-arrow-left" aria-hidden="true"></i></button>
            </div>
        </div>

TRWLASystemMaster/TRWLASystemMaster/Views/Contents/Index.cshtml
@model IEnumerable<TRWLASystemMaster.Models.DB.Content>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/VolunteerLoggedInPage.cshtml";
}

<div class="jumbotron">
    <h1>TRWLA Content</h1>
    <div class="quoteform"></div>
    <div class="quote1form"></div>
    <div class="quote2form"></div>
</div>


<div class="form-inline">
    <div class="form-group" style="margin-right:10px;">
        <h2 style="z-index:100; position:relative; background-color:transparent;">Search Content</h2>
        @using (Html.BeginForm())
        {
            <div class="form-inline" style="margin-bottom:10px;">
                <p data-toggle="tooltip" title="Search by name" class="form-group">
                    @Html.TextBox("searchString", "", new { placeholder = "Name of Content", @class = "form-control", style = "width:100%;" })
                </p>

                <p class="form-group">
                    <button data-toggle="tooltip" title="Search" type="submit" value="Search" class="btn"><i class="fa fa-search" aria-hidden="true" style="color:black;"></i></button>
                </p>
                <div class="form-group">
                    <button data-toggle="tooltip" title="Upload new Content" type="button" class="btn" onclick="location.href='@Url.Action("Create", "Contents")'"><i class="fa fa-plus" aria-hidden="true"></i></button>
                </div>
            </div>
        }
        <div class="form-group">
            <select data-toggle="tooltip" title="Filter Content" id="UrlList" onchange="doNavigate()" class="form-control" style="margin-bottom:20px; width:280px;">
                <option value="">Filter by...</option>
                <option value="@Url.Action("Index", "Contents", new { all = "all" })'">Show All</option>
                <option value="@Url.Action("Index", "Contents", new { sortOrder = "name" })'">Name</option>
                <option value="@Url.Action("Index", "Contents", new { locked = "locked" })'">Locked</option>
                <option value="@Url.Action("Index", "Contents", new { unlocked = "unlocked" })'">Unlocked</option>
            </select>
        </div>
    </div>
</div>

<script>
    function doNavigate() {
        window.location.href = document.getElementById("UrlList").value;
    }
</script>


@*<div class="form-inline" style="margin-bottom:10px;">
    <div class="form-group">
        @using (Html.BeginForm())
        {
            <p>
                @Html.Label("Find by name:") @Html.TextBox("searchString")
                <button type="submit" value="Search" class="btn"><i class="fa fa-search" aria-hidden="true"></i>Search</button>
            </p>
        }
    </div>
</div>
<div class="form-inline" style="margin-bottom:20px;">
    <div class="form-group">
        <p>
            @Html.Label("Filter by:")
        </p>
    </div>
    <div class="form-group">
        <button type="button" class="btn" onclick="location.href='@Url.Action("Index", "Contents", new { sortOrder = ViewBag.NameSortParm })'">Name</button>
    </div>
    <div class="form-group">
        <button type="button" class="btn" onclick="location.href='@Url.Action("Index", "Contents", new { locked = ViewBag.SurnameSortParm })'">Locked</button>
    </div>
    <div class="form-group">
        <button type="button" class="btn" onclick="location.href='@Url.Action("Index", "Contents", new { unlocked = ViewBag.SurnameSortParm })'">Unlocked</button>
    </div>
    <div class="form-group">
        <button type="button" class="btn" onclick="location.href='@Url.Action("Index", "Contents", new { all = ViewBag.SurnameSortParm })'">All</button>
    </div>
</div>*@

<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            Status
        </th>
        <th>
            Description
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.Where(p => p.ContentID != 1))
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Content_Name)
            </td>
            <td>
                @if (item.Content_Status == 1)
                {
                    <p ><i data-toggle="tooltip" title="This content is locked. 
                       It cannot be seen by students." class="fa fa-lock" aria-hidden="true"></i></p>
                }
                @if (item.Content_Status == 0)
                {
                    <p ><i data-toggle="tooltip" title="This content is unlocked. 
                       It can be seen by students."  class="fa fa-unlock" aria-hidden="true"></i></p>
                }

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Content_Description)
            </td>
            <td>
                <a href="@Url.Action("Details", new { id=item.ContentID })" data-toggle="tooltip" title="Details"><i class="fa fa-info-circle" aria-hidden="true"></i></a>

            </td>
        </tr>
    }

</table>

<div class="form-inline" style="float:right; margin-bottom:20px; margin-top:10px;">
    <div class="form-group" data-toggle="tooltip" title="Return to the Main Menu">
                <button  type="button" class="btn" onclick="location.href='@Url.Action("Index", "TRWLASchedules")'"><i class="fa fa-arrow-left" aria-hidden="true"></i></button>
    </div>
</div>