TRWLASystemMaster/TRWLASystemMaster/Models/DB/UniqueCode.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TRWLASystemMaster.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniqueCode
    {
        public int UniID { get; set; }
        [Required(ErrorMessage = "A unique code is required")]
        [Display(Name = "Unique Code")]
        public int Code { get; set; }
        public System.DateTime stamptime { get; set; }
    }
}

TRWLASystemMaster/TRWLASystemMaster/Controllers/UniqueCodeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TRWLASystemMaster.Models.DB;

namespace TRWLASystemMaster.Controllers
{
    public class UniqueCodeController : Controller
    {
        /// <summary>
        /// Code that generates the unique code
        /// </summary>
        private TWRLADB_Staging_V2Entities8 db = new TWRLADB_Staging_V2Entities8();
        // GET: UniqueCode
        public ActionResult UniqueCode()
        {
            return View();
        }

        public ActionResult NewUniCode()
        {



            return View(db.UniqueCodes.ToList());
        }


        public ActionResult AddCode()
        {

            Random rnd = new Random();

            UniqueCode unic = new UniqueCode();

            unic.Code = rnd.Next(10000, 99999);
            unic.stamptime = DateTime.Now;

            db.UniqueCodes.Add(unic);
            db.SaveChanges();

            ViewBag.Message = unic;
            return View();
        }
    }
}

TRWLASystemMaster/TRWLASystemMaster/Views/UniqueCode/AddCode.cshtml
@model TRWLASystemMaster.Models.DB.UniqueCode

@{
    ViewBag.Title = "AddCode";
    Layout = "~/Views/Shared/VolunteerLoggedInPage.cshtml";
}

<h2>AddCode</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UniqueCode</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.stamptime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.stamptime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.stamptime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TRWLASystemMaster/TRWLASystemMaster/Views/UniqueCode/EnterUniCode.cshtml
@{
    ViewBag.Title = "EnterUniCode";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="jumbotron">
    <h2>EnterUniCode</h2>
</div>


<input type="password"/>
<button>@Html.ActionLink("Enter", "Create", "Volunteers") </button>

TRWLASystemMaster/TRWLASystemMaster/Views/UniqueCode/NewUniCode.cshtml
@model IEnumerable<TRWLASystemMaster.Models.DB.UniqueCode>


@{
    ViewBag.Title = "NewUniCode";
    Layout = "~/Views/Shared/VolunteerLoggedInPage.cshtml";
}

<h2>NewUniCode</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.stamptime)
        </th>
        <th></th>
    </tr>
    @Html.ActionLink("TRWLA", "AddCode", "UniqueCode")

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.stamptime)
            </td>
            <td>

                @*<a href="@Url.Action("Edit", new { id=item.UserTypeID  })" data-toggle="tooltip" title="Edit"><i class="fa fa-pencil" aria-hidden="true"></i></a> |

                    <a href="@Url.Action("Details", new { id=item.UserTypeID  })" data-toggle="tooltip" title="Details"><i class="fa fa-info-circle" aria-hidden="true"></i></a> |

                    <a href="@Url.Action("Delete", new { id=item.UserTypeID  })" data-toggle="tooltip" title="Delete"><i class="fa fa-trash-o" aria-hidden="true"></i></a> |*@


            </td>
        </tr>
    }

</table>

TRWLASystemMaster/TRWLASystemMaster/Views/UniqueCode/UniqueCode.cshtml
@{
    Layout = "~/Views/Shared/VolunteerLoggedInPage.cshtml";
}

<div class="jumbotron">
    <h2>Generate Unique Code</h2>
</div>


<ceneter><p>Unique codes can only be used once</p></ceneter>

    @* Generate Unique Code For vols'*@


    @using (Html.BeginForm())
    {
        <p>
            <button class="btn btn-round btn-round" style="color:#9b16d8">Generate Unique Code</button>
        </p>
    }




<table class="table">
    <tr>
        <th>
            Code
        </th>
        <th>
            Status
        </th>
            <th></th>
    </tr>


    <tr>
        <td><!-- Record # 1 -->
           124357
        </td>
        <td>
            <span class="badge badge-success">Active</span>
        </td>
    </tr>

    <tr>

        <td>
            <!-- Record # 2 -->
            258478
        </td>
        <td>
            <span class="badge badge-danger">Inactive</span>
        </td>

    </tr>

    <tr>

        <td>
            <!-- Record #  3-->
            123546
        </td>
        <td>
            <span class="badge badge-success">Active</span>
        </td>
    </tr>

    <tr>
        <td>
            <!-- Record # 4 -->
            859756
        </td>
        <td>
            <span class="badge badge-danger">Inactive</span>
        </td>
    </tr>

    <tr>
        <td>
            <!-- Record # 5 -->
            745896
        </td>
        <td>
            <span class="badge badge-success">Active</span>
        </td>
    </tr>

    <tr>
        <td>
            <!-- Record # 6 -->
            1452369
        </td>
        <td>
            <span class="badge badge-danger">Inactive</span>
        </td>
    </tr>

</table>