TRWLASystemMaster/TRWLASystemMaster/Models/DB/GuestSpeaker.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TRWLASystemMaster.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestSpeaker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GuestSpeaker()
        {
            this.FunctionEvents = new HashSet<FunctionEvent>();
            this.GenEvents = new HashSet<GenEvent>();
        }
    
        public int GuestSpeakerID { get; set; }

        [Required(ErrorMessage = "A name for the guest speaker is required")]
        [Display(Name = "name")]
        [StringLength(50, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 2)]
        public string GuestSpeaker_Name { get; set; }

        [Required(ErrorMessage = "A surname for the guest speaker is required")]
        [Display(Name = "surname")]
        [StringLength(50, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 2)]
        public string GuestSpeaker_Surname { get; set; }

        [Required(ErrorMessage = "A phone number for the guest speaker is required")]
        [Display(Name = "phone number")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid Phone number")]
        public string GuestSpeaker_Phone { get; set; }
        
        [Required(ErrorMessage = "An email address is required")]
        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        [RegularExpression(@"^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$", ErrorMessage = "Please Enter Correct Email Address")]
        public string GuestSpeaker_Email { get; set; }
        public string GuestSpeaker_PictureLink { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FunctionEvent> FunctionEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GenEvent> GenEvents { get; set; }
    }
}

TRWLASystemMaster/TRWLASystemMaster/Controllers/GuestSpeakerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TRWLASystemMaster.Models;
using TRWLASystemMaster.Models.DB;

namespace TRWLASystemMaster.Controllers
{
    public class GuestSpeakerController : Controller
    {
        private TWRLADB_Staging_V2Entities8 db = new TWRLADB_Staging_V2Entities8();

        public ActionResult Details(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                GuestSpeaker guestSpeaker = db.GuestSpeakers.Find(id);
                if (guestSpeaker == null)
                {
                    return HttpNotFound();
                }
                return View(guestSpeaker);
            }
            catch (Exception)
            {
                return RedirectToAction("ErrorPage", "TRWLASchedules");
            }
        }

        // GET: GuestSpeakers1
        public ActionResult Index(string sortOrder, string searchString, string ascending)
        {
            try
            {
                ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
                ViewBag.SurnameSortParm = String.IsNullOrEmpty(sortOrder) ? "sur_desc" : "Surname";
                ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";



                var guestSpeaker = from s in db.GuestSpeakers
                                   select s;

                if (!String.IsNullOrEmpty(searchString))
                {
                    guestSpeaker = guestSpeaker.Where(s => s.GuestSpeaker_Name.Contains(searchString)
                                           || s.GuestSpeaker_Surname.Contains(searchString));
                }

                if (!String.IsNullOrEmpty(sortOrder))
                {
                    guestSpeaker = guestSpeaker.OrderByDescending(s => s.GuestSpeaker_Name);
                }

                if (!String.IsNullOrEmpty(ascending))
                {
                    guestSpeaker = guestSpeaker.OrderBy(s => s.GuestSpeaker_Name);
                }



                return View(guestSpeaker.ToList());
            }
            catch (Exception)
            {
                return RedirectToAction("ErrorPage", "TRWLASchedules");
            }
        }



        // GET: GuestSpeakers1/Details/5


        // GET: GuestSpeakers1/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: GuestSpeakers1/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "GuestSpeakerID,GuestSpeaker_Name,GuestSpeaker_Surname,GuestSpeaker_Phone,GuestSpeaker_Email,GuestSpeaker_PictureLink")] GuestSpeaker guestSpeaker)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int i = db.GuestSpeakers.Count();

                    if (i != 0)
                    {

                        AuditLog myAudit = new AuditLog();
                        myAudit.DateDone = DateTime.Now;
                        myAudit.TypeTran = "Create";
                        myAudit.SYSUserProfileID = (int)Session["User"];
                        myAudit.TableAff = "GuestSpeaker";
                        db.AuditLogs.Add(myAudit);

                        int k = db.GuestSpeakers.Max(p => p.GuestSpeakerID);
                        int max = k + 1;

                        guestSpeaker.GuestSpeakerID = max;

                        db.GuestSpeakers.Add(guestSpeaker);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }

                    else
                    {
                        db.GuestSpeakers.Add(guestSpeaker);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }


                }

                return View(guestSpeaker);
            }
            catch (Exception)
            {
                return RedirectToAction("ErrorPage", "TRWLASchedules");
            }
        }

        // GET: GuestSpeakers1/Edit/5
        public ActionResult Edit(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                GuestSpeaker guestSpeaker = db.GuestSpeakers.Find(id);
                if (guestSpeaker == null)
                {
                    return HttpNotFound();
                }
                return View(guestSpeaker);
            }
            catch (Exception)
            {
                return RedirectToAction("ErrorPage", "TRWLASchedules");
            }
        }

        // POST: GuestSpeakers1/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "GuestSpeakerID,GuestSpeaker_Name,GuestSpeaker_Surname,GuestSpeaker_Phone,GuestSpeaker_Email,GuestSpeaker_PictureLink")] GuestSpeaker guestSpeaker)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    AuditLog myAudit = new AuditLog();
                    myAudit.DateDone = DateTime.Now;
                    myAudit.TypeTran = "Update";
                    myAudit.SYSUserProfileID = (int)Session["User"];
                    myAudit.TableAff = "GuestSpeaker";
                    db.AuditLogs.Add(myAudit);


                    db.Entry(guestSpeaker).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(guestSpeaker);
            }
            catch (Exception)
            {
                return RedirectToAction("ErrorPage", "TRWLASchedules");
            }
        }

        // GET: GuestSpeakers1/Delete/5
        public ActionResult Delete(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                GuestSpeaker guestSpeaker = db.GuestSpeakers.Find(id);
                if (guestSpeaker == null)
                {
                    return HttpNotFound();
                }
                return View(guestSpeaker);
            }
            catch (Exception)
            {
                return RedirectToAction("ErrorPage", "TRWLASchedules");
            }
        }

        // POST: GuestSpeakers1/Delete/5
        [HttpPost, ActionName("Details")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                GuestSpeaker guestSpeaker = db.GuestSpeakers.Find(id);

                try
                {
                    db.GuestSpeakers.Remove(guestSpeaker);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    TempData["notice"] = " Please note: This guest speaker is assigned to an event and cannot be deleted.";
                    return View(guestSpeaker);
                }
            }
            catch (Exception)
            {
                return RedirectToAction("ErrorPage", "TRWLASchedules");
            }

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TRWLASystemMaster/TRWLASystemMaster/Controllers/GuestSpeakersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TRWLASystemMaster.Models;

namespace TRWLASystemMaster.Controllers
{
    public class GuestSpeakers1Controller : Controller
    {
        private TWRLADB_Staging_V2Entities db = new TWRLADB_Staging_V2Entities();

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GuestSpeaker guestSpeaker = db.GuestSpeakers.Find(id);
            if (guestSpeaker == null)
            {
                return HttpNotFound();
            }
            return View(guestSpeaker);
        }

        // GET: GuestSpeakers1
        public ActionResult Index(string sortOrder, string searchString)
        {

            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.SurnameSortParm = String.IsNullOrEmpty(sortOrder) ? "sur_desc" : "Surname";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";



            var guestSpeaker = from s in db.GuestSpeakers
                               select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                guestSpeaker = guestSpeaker.Where(s => s.GuestSpeaker_Name.Contains(searchString)
                                       || s.GuestSpeaker_Surname.Contains(searchString));
            }


            switch (sortOrder)
            {
                case "name_desc":
                    guestSpeaker = guestSpeaker.OrderByDescending(s => s.GuestSpeaker_Name);
                    break;
                case "sur_desc":
                    guestSpeaker = guestSpeaker.OrderByDescending(s => s.GuestSpeaker_Surname);
                    break;
                case "Surname":
                    guestSpeaker = guestSpeaker.OrderByDescending(s => s.GuestSpeaker_Surname);
                    break;
                default:
                    guestSpeaker = guestSpeaker.OrderBy(s => s.GuestSpeaker_Name);
                    break;
            }

            return View(guestSpeaker.ToList());
        }



        // GET: GuestSpeakers1/Details/5


        // GET: GuestSpeakers1/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: GuestSpeakers1/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "GuestSpeakerID,GuestSpeaker_Name,GuestSpeaker_Surname,GuestSpeaker_Phone,GuestSpeaker_Email,GuestSpeaker_PictureLink")] GuestSpeaker guestSpeaker)
        {
            if (ModelState.IsValid)
            {
                int i = db.GuestSpeakers.Count();

                if (i != 0)
                {
                    int k = db.GuestSpeakers.Max(p => p.GuestSpeakerID);
                    int max = k + 1;

                    guestSpeaker.GuestSpeakerID = max;

                    db.GuestSpeakers.Add(guestSpeaker);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                else
                {
                    db.GuestSpeakers.Add(guestSpeaker);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }


            }

            return View(guestSpeaker);
        }

        // GET: GuestSpeakers1/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GuestSpeaker guestSpeaker = db.GuestSpeakers.Find(id);
            if (guestSpeaker == null)
            {
                return HttpNotFound();
            }
            return View(guestSpeaker);
        }

        // POST: GuestSpeakers1/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "GuestSpeakerID,GuestSpeaker_Name,GuestSpeaker_Surname,GuestSpeaker_Phone,GuestSpeaker_Email,GuestSpeaker_PictureLink")] GuestSpeaker guestSpeaker)
        {
            if (ModelState.IsValid)
            {
                db.Entry(guestSpeaker).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(guestSpeaker);
        }

        // GET: GuestSpeakers1/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GuestSpeaker guestSpeaker = db.GuestSpeakers.Find(id);
            if (guestSpeaker == null)
            {
                return HttpNotFound();
            }
            return View(guestSpeaker);
        }

        // POST: GuestSpeakers1/Delete/5
        [HttpPost, ActionName("Details")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

            GuestSpeaker guestSpeaker = db.GuestSpeakers.Find(id);

            try
            {
                db.GuestSpeakers.Remove(guestSpeaker);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                TempData["notice"] = " Please note: This guest speaker is assigned to an event and cannot be deleted.";
                return View(guestSpeaker);
            }

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TRWLASystemMaster/TRWLASystemMaster/Views/GuestSpeakers/Create.cshtml
@model TRWLASystemMaster.Models.GuestSpeaker

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/VolunteerLoggedInPage.cshtml";
}

<div class="jumbotron">
    <h2>Register Guest Speaker</h2>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Name:", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GuestSpeaker_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GuestSpeaker_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Surname: ", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GuestSpeaker_Surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GuestSpeaker_Surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Phone Number:", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GuestSpeaker_Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GuestSpeaker_Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Email:", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GuestSpeaker_Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GuestSpeaker_Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Picture Link:", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GuestSpeaker_PictureLink, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GuestSpeaker_PictureLink, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-inline" style="float:right; margin-bottom:10px; margin-top:10px;">
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button class="btn btn-default btn-round" data-toggle="modal" data-target="#Create" style="color:#9b16d8">
                    Create
                </button>
            </div>

        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 ">
                <div>
                    @Html.ActionLink("Return", "Index", "GuestSpeakers1", new { @class = "btn btn-default btn-round", @style = "color:#9b16d8" })
                </div>
            </div>
        </div>
    </div>

}

TRWLASystemMaster/TRWLASystemMaster/Views/GuestSpeakers/Delete.cshtml
@model TRWLASystemMaster.Models.GuestSpeaker

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/VolunteerLoggedInPage.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GuestSpeaker</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GuestSpeaker_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GuestSpeaker_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GuestSpeaker_Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GuestSpeaker_Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GuestSpeaker_Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GuestSpeaker_Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GuestSpeaker_Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GuestSpeaker_Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GuestSpeaker_PictureLink)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GuestSpeaker_PictureLink)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TRWLASystemMaster/TRWLASystemMaster/Views/GuestSpeakers/Index.cshtml
@model IEnumerable<TRWLASystemMaster.Models.GuestSpeaker>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/VolunteerLoggedInPage.cshtml";
}

<div class="jumbotron">
    <h2>TRWLA Guest Speakers</h2>
</div>


<div class="form-group">
    @using (Html.BeginForm())
    {
        <p>
            @Html.Label("Find by name:") @Html.TextBox("searchString")
            <input type="submit" value="Search" class="btn btn-default btn-round" , style="color:#9b16d8" />
        </p>
    }
</div>

<div class="form-inline" style="margin-bottom:10px;">
    <div class="form-group">@Html.Label("Order by:")</div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10 ">

            <div class="btn btn-default btn-round" , style="color:#9b16d8">
                @Html.ActionLink("Name", "Index", new { sortOrder = ViewBag.NameSortParm })
            </div>
        </div>
    </div>
</div>


<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            Surname
        </th>
        <th>
            Phone Number
        </th>
        <th>
            Email Address
        </th>
        <th>
            Picture Link
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.GuestSpeaker_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GuestSpeaker_Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GuestSpeaker_Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GuestSpeaker_Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GuestSpeaker_PictureLink)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.GuestSpeakerID }) |
                @Html.ActionLink("Details", "Details", new { id = item.GuestSpeakerID })
            </td>
        </tr>
    }

</table>

<div class="form-inline" style="float:right; margin-bottom:20px; margin-top:10px;">
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <div>
                @Html.ActionLink("Register Guest Speaker", "Create", "GuestSpeakers1", new { @class = "btn btn-default btn-round", @style = "color:#9b16d8" })
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10 ">
            <div class="btn btn-default btn-round" , style="color:#9b16d8">
                @Html.ActionLink("Return", "Index", "TRWLASchedules")
            </div>
        </div>
    </div>
</div>